### ISSUE TITLE
Uncaught SyntaxError: Unexpected token, both as node module and svelte demos

### ISSUE THREAD

**Issue by pax** [jutunen/piano-keys#1]
As node module: `Uncaught SyntaxError: Unexpected token 'export'` : `custom-piano-keys-node.js:2`

On both svelte demos I get: `Uncaught SyntaxError: Unexpected token '<'` : `custom-piano-keys-node.js:1`

**Comment by jutunen** [comment]
You shouldn't be using the node version of the component with svelte demos. As the readme.md says:
*Copy custom-piano-keys.js in to public directory before building!*

About the first issue, I have no idea what's wrong in your configuration, maybe this could help:
https://stackoverflow.com/questions/38296667/getting-unexpected-token-export

**Comment by pax** [comment]
That was it, (`custom-piano-keys.js` -> `public`), clumsy me, thank you.

**Comment by jutunen** [comment]
No problem. I noticed that you have been very generous with stars. So, could you please... you know... I'd appreciate... ;-)
